baseURL = "https://pgregory.net/"
languageCode = "en-us"
title = "Gregory Petrosyan's home page"
theme = "plain"
publishDir = "docs"
disableHugoGeneratorInject = true
enableGitInfo = true

[permalinks]
  projects = "/:filename/"

[params]
  description = "Gregory Petrosyan's home page"
  shortName = "pgregory.net"

[params.author]
  name = "Gregory Petrosyan"
  email = "pgregory@pgregory.net"

[taxonomies]

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 8
